//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LombardWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleID { get; set; }
        public System.DateTime Date { get; set; }
        public int StaffID { get; set; }
        public int Cost { get; set; }
        public int ProductID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
